name: Update to current time

on:
  schedule:
    - cron: '* * * * *'

jobs:
  time:
    name: Update files to current time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tag
        uses: actions/checkout@v3
      - id: timestamp
        name: Update TIMESTAMP file with epoch TIMESTAMP
        run: |
          date +%s | tee TIMESTAMP
      - id: datetime
        name: Update DATETIME file with ISO 8601 datetime
        run: |
          date -u +"%Y-%m-%dT%H:%M:%S%z" | tee DATETIME
      - name: Commit the new time
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update time to ${{ steps.datetime.outputs.stdout }}'
